{"tag": "function", "depth": 1, "time": 1758735472.2393425, "data": {"name": "serial_send", "call_args": {"command": "aaaaa", "index": 0}, "start_time": 1758735472.2393425, "traceback": "\u4e32\u53e3\u672a\u6253\u5f00\uff0c\u8df3\u8fc7\u53d1\u9001\uff1aaaaaa", "ret": null, "end_time": 1758735472.2393425}}
{"tag": "function", "depth": 1, "time": 1758735474.507511, "data": {"name": "get", "call_args": {"address": "http://192.168.1.1"}, "start_time": 1758735472.2393425, "ret": null, "end_time": 1758735474.507511}}
{"tag": "function", "depth": 1, "time": 1758735474.5085485, "data": {"name": "serial_login", "call_args": {"password": "79d05758", "username": "root", "index": 0, "timeout": 10}, "start_time": 1758735474.507511, "traceback": "Traceback (most recent call last):\n  File \"C:\\Program Files\\Python39\\lib\\site-packages\\tp_airtest_selenium\\__init__.py\", line 31, in wrapper\n    res = f(*args, **kwargs)\n  File \"C:\\Program Files\\Python39\\lib\\site-packages\\tp_airtest_selenium\\proxy.py\", line 635, in serial_login\n    serial_manager = self._get_serial_manager(index)\n  File \"C:\\Program Files\\Python39\\lib\\site-packages\\tp_airtest_selenium\\proxy.py\", line 619, in _get_serial_manager\n    print(\"\u9519\u8bef\uff1a\u9ed8\u8ba4\u4e32\u53e3\u672a\u914d\u7f6e\")\nOSError: [Errno 22] Invalid argument\n", "end_time": 1758735474.5085485}}
{"tag": "info", "depth": 0, "time": 1758735474.5105858, "data": {"name": "Final Error", "traceback": "Traceback (most recent call last):\n  File \"C:\\Program Files\\Python39\\lib\\site-packages\\airtest\\cli\\runner.py\", line 72, in runTest\n    exec(compile(code.encode(\"utf-8\"), pyfilepath, 'exec'), self.scope)\n  File \"C:\\Users\\Administrator\\Desktop\\AirtestMulti\\release\\case\\test1-1.air\\test1-1.py\", line 17, in <module>\n    driver.serial_login(password=\"79d05758\")\n  File \"C:\\Program Files\\Python39\\lib\\site-packages\\tp_airtest_selenium\\__init__.py\", line 31, in wrapper\n    res = f(*args, **kwargs)\n  File \"C:\\Program Files\\Python39\\lib\\site-packages\\tp_airtest_selenium\\proxy.py\", line 635, in serial_login\n    serial_manager = self._get_serial_manager(index)\n  File \"C:\\Program Files\\Python39\\lib\\site-packages\\tp_airtest_selenium\\proxy.py\", line 619, in _get_serial_manager\n    print(\"\u9519\u8bef\uff1a\u9ed8\u8ba4\u4e32\u53e3\u672a\u914d\u7f6e\")\nOSError: [Errno 22] Invalid argument\n"}}
